### ISSUE TITLE
ShaderHandler.cs m_InsertSubProgramCommand need to put id  in

### ISSUE THREAD

**Issue by GeorgeVan** [Unity-Technologies/UnityDataTools#8]
"INSERT INTO shader_subprograms(shader, sub_shader, pass, pass_name, sub_program, hw_tier, shader_type, api) VALUES(@shader, @sub_shader, @pass, @pass_name, @sub_program, @hw_tier, @shader_type, @api)";

Should be:

"INSERT INTO shader_subprograms(id, shader, sub_shader, pass, pass_name, sub_program, hw_tier, shader_type, api) VALUES(@id, @shader, @sub_shader, @pass, @pass_name, @sub_program, @hw_tier, @shader_type, @api)";

**Comment by francis-page** [comment]
Thanks for reporting this! It's fixed.
